### ISSUE TITLE
prospective reconstruction

### ISSUE THREAD

**Issue by XWangBin** [yhao-z/T2LR-Net#2]
张博士您好！
首先感谢您的卓越贡献以及祝贺您的T2LR-Net被CIBM发表，我在使用OCMR数据集进行prospective reconstruction实验时，不能正常进行，可能是我的代码写的有问题。请问您能否分享一下您的训练过程以供学习，再次感谢！

**Comment by yhao-z** [comment]
您好！
很庆幸您能关注我们的工作。很抱歉最近因为各种事情没能及时的开源代码。我近几天会及时整理并发布论文代码。
关于prospective实验的问题，我当时也是遇到了问题。我先在这里给您简单提供一个方案，希望能够对您有帮助。
prospective实验跟多线圈实验实际上是相同的。问题在于（1）线圈敏感度估计（2）数据归一化
（1）因为vista模板没有自校准ACS区域，所以不能用常规方法估计。但是vista模板在时间维度平均之后会得到一张满填充的二维k空间，可以用这个来估计，详情可以看VISTA的论文。
（2）数据归一化我推荐训练多线圈模型的时候在k空间归一化，而不是在图像域。我认为这样更符合MRI的特殊情况。

**Comment by XWangBin** [comment]
再次感谢您的解答，这对我帮助很大。
祝一切顺利
